// M=1 GQA attention for streaming decoder single-token inference.
// Custom CUDA kernel replaces flash_attn_windowed when seq_len_q == 1.
//
// Design: 1 warp (32 threads) per query head, 4 dims per thread.
// Online softmax + per-thread V accumulation = no cross-thread reduction.

use candle_core::backend::BackendStorage;
use candle_core::cuda_backend::cudarc::driver::{LaunchConfig, PushKernelArg};
use candle_core::{CpuStorage, Layout, Result, Shape, Tensor};
use half::bf16;

mod ptx {
    // Generated by build.rs via cudaforge: compiles src/kernels/m1_attention.cu → PTX
    include!(concat!(env!("OUT_DIR"), "/ptx.rs"));
}

struct M1GqaAttn {
    scale: f32,
    window_size: usize,
}

impl M1GqaAttn {
    fn cuda_fwd(
        &self,
        q: &candle_core::CudaStorage,
        q_l: &Layout,
        k: &candle_core::CudaStorage,
        k_l: &Layout,
        v: &candle_core::CudaStorage,
        v_l: &Layout,
    ) -> Result<(candle_core::CudaStorage, Shape)> {
        let dev = q.device();
        let out_shape = q_l.shape().clone();

        let q = q.as_cuda_slice::<bf16>()?;
        let k = k.as_cuda_slice::<bf16>()?;
        let v = v.as_cuda_slice::<bf16>()?;

        let q = q.slice(q_l.start_offset()..);
        let k = k.slice(k_l.start_offset()..);
        let v = v.slice(v_l.start_offset()..);

        let (_b_sz, _seq_q, num_q_heads, _head_dim) = q_l.shape().dims4()?;
        let (_b_sz, kv_len, num_kv_heads, _head_dim) = k_l.shape().dims4()?;
        let gqa_ratio = (num_q_heads / num_kv_heads) as i32;

        let elem_count = out_shape.elem_count();
        let dst = unsafe { dev.alloc::<bf16>(elem_count)? };

        let func = dev.get_or_load_custom_func(
            "m1_gqa_attn_bf16",
            "m1_attention",
            ptx::M1_ATTENTION,
        )?;

        let cfg = LaunchConfig {
            grid_dim: (num_q_heads as u32, 1, 1),
            block_dim: (32, 1, 1),
            shared_mem_bytes: 0,
        };

        let kv_len_i32 = kv_len as i32;
        let num_kv_heads_i32 = num_kv_heads as i32;
        let window_size_i32 = self.window_size as i32;

        let mut builder = func.builder();
        builder.arg(&q);
        builder.arg(&k);
        builder.arg(&v);
        builder.arg(&dst);
        builder.arg(&kv_len_i32);
        builder.arg(&num_kv_heads_i32);
        builder.arg(&gqa_ratio);
        builder.arg(&self.scale);
        builder.arg(&window_size_i32);

        unsafe { builder.launch(cfg) }.map_err(candle_core::Error::wrap)?;

        let dst = candle_core::CudaStorage::wrap_cuda_slice(dst, dev.clone());
        Ok((dst, out_shape))
    }
}

impl candle_core::CustomOp3 for M1GqaAttn {
    fn name(&self) -> &'static str {
        "m1-gqa-attn"
    }

    fn cpu_fwd(
        &self,
        _: &CpuStorage,
        _: &Layout,
        _: &CpuStorage,
        _: &Layout,
        _: &CpuStorage,
        _: &Layout,
    ) -> Result<(CpuStorage, Shape)> {
        candle_core::bail!("m1-gqa-attn requires CUDA")
    }

    fn cuda_fwd(
        &self,
        q: &candle_core::CudaStorage,
        q_l: &Layout,
        k: &candle_core::CudaStorage,
        k_l: &Layout,
        v: &candle_core::CudaStorage,
        v_l: &Layout,
    ) -> Result<(candle_core::CudaStorage, Shape)> {
        self.cuda_fwd(q, q_l, k, k_l, v, v_l)
    }
}

/// M=1 GQA attention with sliding window. Drop-in replacement for
/// flash_attn_windowed when seq_len_q == 1 (streaming decode).
///
/// Input layout (flash attention format):
///   q: [batch, 1, num_q_heads, head_dim]
///   k: [batch, kv_len, num_kv_heads, head_dim]
///   v: [batch, kv_len, num_kv_heads, head_dim]
///
/// Output: [batch, 1, num_q_heads, head_dim]
pub fn m1_attn_windowed(
    q: &Tensor,
    k: &Tensor,
    v: &Tensor,
    softmax_scale: f32,
    window_size: usize,
) -> Result<Tensor> {
    let op = M1GqaAttn {
        scale: softmax_scale,
        window_size,
    };
    q.apply_op3(k, v, op)
}
